### ISSUE TITLE
Creo que la J y la H êttán cambiâh en er trâccrîttôh

### ISSUE THREAD

**Issue by pr3ssh** [andalugeeks/andaluh-cordova#2]
![photo5902100520535962102](https://user-images.githubusercontent.com/404339/74026599-d37ffa80-49a6-11ea-8014-48caa8b49c0a.jpg)
![photo5902100520535962103](https://user-images.githubusercontent.com/404339/74026605-d549be00-49a6-11ea-9f1e-ff9281669217.jpg)

**Comment by fontanon** [comment]
It might be somewhat confusing, but the J/H button is actually a switch. When you see 'J' means you're using 'H' and viceversa.
